cat("*** Starting R using .Rprofile generated by PsN ***\n")
cat("Using library path /apps/leuven/rocky8/icelake/2021a/software/PsN/5.3.0-foss-2021a/lib/perl5/site_perl/5.32.1/PsN_5_3_0/Rlib\n")
.libPaths('/apps/leuven/rocky8/icelake/2021a/software/PsN/5.3.0-foss-2021a/lib/perl5/site_perl/5.32.1/PsN_5_3_0/Rlib')
