---
NONMEM_directory: /apps/leuven/rocky8/icelake/2021a/software/NONMEM/7.5.0-GCC-10.3.0-MPICH-3.4.2/run/nmfe75
NONMEM_version: 7.5
PsN_version: 5.3.0
command_line: /apps/leuven/rocky8/icelake/2021a/software/PsN/5.3.0-foss-2021a/bin/execute -nodes=2 -threads=72 -nm_version=nm750 -parafile=mpilinux8.pnm 1.mod
common_options:
  abort_on_fail: 0
  accepted_ofv_difference: 0.5
  add_retries: 0
  always_datafile_in_nmrun: 0
  check_nmtran: 0
  clean: 3
  compress: 0
  condition_number_limit: 1000
  correlation_limit: 0.85
  crash_restarts: 5
  debug_rmd: 0
  degree: 0.1
  directory: /vsc-hard-mounts/leuven-data/357/vsc35700/Fluco_revised/R_code/Zhigang/modelfit_dir1/
  display_iterations: 1
  handle_crashes: 1
  handle_msfo: 0
  html: 0
  large_omega_cv_limit: 0.8
  large_sigma_cv_limit: 0.8
  large_theta_cv_limit: 0.5
  last_est_complete: 0
  lsf_sleep: 3
  min_retries: 0
  missing_data_token: -99
  model_subdir: 0
  near_bound_sign_digits: 2
  near_zero_boundary_limit: 0.01
  nice: 19
  nm_output: 'ext,cov,cor,coi,phi,phm,cnv,smt,rmt,npd,npe,npi,npl,ets'
  nm_version: nm750
  nmfe: 1
  nodes: 2
  parafile: /vsc-hard-mounts/leuven-data/357/vsc35700/Fluco_revised/R_code/Zhigang/mpilinux8.pnm
  pdf: 1
  picky: 0
  prepend_model_file_name: 0
  quick_summarize: 0
  retries: 0
  rmarkdown: 1
  rplots: 0
  run_on_lsf: 0
  run_on_sge: 0
  run_on_slurm: 0
  run_on_torque: 0
  run_on_ud: 0
  run_on_zink: 0
  seed: 588554
  send_email: 0
  shrinkage: 0
  sign_digits_off_diagonals: 2
  significant_digits_accept: 0
  so: 0
  template_directory_rplots: /vsc-hard-mounts/leuven-apps/rocky8/icelake/2021a/software/PsN/5.3.0-foss-2021a/lib/perl5/site_perl/5.32.1/PsN_5_3_0/R-scripts
  template_file_rplots: execute_default.Rmd
  threads: 72
  tweak_inits: 1
  verbose: 0
  zip: 1
copied_files:
  - 1.lst
  - 1.ext
  - 1.cov
  - 1.cor
  - 1.coi
  - 1.phi
  - sdtab1
  - cotab1
  - catab1
  - patab1
  - fulltab1
finish_time: 2024-04-15 15:58:56
model_files:
  - /vsc-hard-mounts/leuven-data/357/vsc35700/Fluco_revised/R_code/Zhigang/1.mod
start_time: 2024-04-15 15:03:39
tool_name: execute
tool_options:
  copy_data: 1
  prepend_options_to_lst: 0
  tail_output: 0
